format_version: 10
pipelines:
  tf-destroy-pipeline: 
    group: terraform-group
    materials:
      mygit: 
        git: https://github.com/lalithvoop/expense-terraform.git
        auto-update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, argument: ["init","-backend-config=env-dev/state.tfvars"], run_if: passed}
                - exec: {command: terraform, argument: ["destroy","-var-file=env-dev/main.tfvars","-auto-approve"], run_if: passed}